# Run: condor_submit phylo_tocris.sub script=phylo_tocris.sh

# request Zamanian Lab server
Accounting_Group = PathobiologicalSciences_Zamanian

# load docker image; request execute server with large data staging
universe = docker
docker_image = zamanianlab/chtc-comgen:v4
Requirements = (Target.HasCHTCStaging == true)

# executable (/home/{net-id}/) and arguments
executable = $(script)
arguments = $(target)

# log, error, and output files
log = $(target)_$(Cluster)_$(Process).log
error = $(target)_$(Cluster)_$(Process).err
output = $(target)_$(Cluster)_$(Process).out

# transfer files in-out of /home/{net-id}/
transfer_input_files =
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# memory, disk and CPU requests
request_cpus = 10
request_memory = 64GB
request_disk = 100GB

# submit 1 job
# queue 1

# submit a job for each directory in tar_list.txt
queue target from tar_list.txt
### END
