# Input data: /staging/groups/zamanian_group/input/$(file)  output.vcf.gz
# Run: condor_submit Aeaeg-filter-snpeff.sub file=output.vcf.gz

# request Zamanian Lab server
Accounting_Group = PathobiologicalSciences_Zamanian

# load docker image; request execute server with large data staging
universe = docker
docker_image = zamanianlab/chtc-dnavc:v1
Requirements = (Target.HasCHTCStaging == true) && \
               (OpSysMajorVer == 7) || (OpSysMajorVer == 8)

# executable (/home/{net-id}/) and arguments
executable = Aeaeg-filter-snpeff.sh
arguments = $(file)

# log, error, and output files
log = $(Cluster)_$(Process).log
error = $(Cluster)_$(Process).err
output = $(Cluster)_$(Process).out

# transfer files in-out of /home/{net-id}/
transfer_input_files =
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# memory, disk and CPU requests
request_cpus = 20
request_memory = 128GB
request_disk = 1000GB

# for jobs > 72 hours
# +LongJob = true

# submit 1 job
queue 1
### END
